server:
  port: ${PORT:8762}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # CORS Global Configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: profile-auth
          uri: lb://profile-service
          predicates:
            - Path=/auth/**
          # No TokenRelay filter for public auth endpoints

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profiles/**
          filters:
            - TokenRelay

        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/content/**
          filters:
            - TokenRelay
            - StripPrefix=1

        - id: planning-service
          uri: lb://planning-service
          predicates:
            - Path=/planning/**
          filters:
            - TokenRelay
            - StripPrefix=1

        - id: assessment-service
          uri: lb://assessment-service
          predicates:
            - Path=/assessment/**
          filters:
            - TokenRelay
            - StripPrefix=1

        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/tracking/**
          filters:
            - TokenRelay
            - StripPrefix=1

  # Security Configuration
  security:
    oauth2:
      client:
        provider:
          keycloak:
            # Client (Browser) needs to access Keycloak via localhost
            authorization-uri: http://localhost:8080/realms/learnsmart/protocol/openid-connect/auth
            # Gateway (Server) needs to access Keycloak via internal network (keycloak:8080)
            token-uri: http://keycloak:8080/realms/learnsmart/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/learnsmart/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/learnsmart/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: api-gateway
            client-secret: ${KEYCLOAK_CLIENT_SECRET:R5dZSvGD8y6diOgI9QRPM3PHaBR8tpDa}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/learnsmart/protocol/openid-connect/certs


eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
## We enable the Actuator API to be able to access <<host>>/actuator/gateway/routes
## We expose the routings that have been automatically detected (all)
## Depending on the ROUTE_TABLES_ENABLED environment variable (true by default)
management:
  endpoint:
    gateway:  
      enabled: ${ROUTE_TABLES_ENABLED:true}
  endpoints:
    web:
      exposure:
        include:
        - '*'